CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers(
id INTEGER(11) AUTO_INCREMENT,
burger_name VARCHAR(50) NOT NULL,
devoured BOOLEAN,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(ID)
);
